name 'trump-dicks'
maintainer 'Jake Gaylor'
maintainer_email 'jhgaylor@gmail.com'
license 'all_rights'
description 'Installs/Configures trump-dicks'
long_description 'Installs/Configures trump-dicks'
version '0.1.0'

depends 'jhg_nginx'
depends 'app_node'
depends 'app_static'
