name 'jhg_nginx'
maintainer 'Jake Gaylor'
maintainer_email 'jhgaylor@gmail.com'
license 'all_rights'
description 'Installs/Configures nginx the way I like it.'
long_description 'Installs/Configures nginx the way I like it.'
version '0.1.0'

depends 'nginx'
depends 'tar'
depends 'nodejs'