name 'diceware'
maintainer 'Jake Gaylor'
maintainer_email 'jhgaylor@gmail.com'
license 'all_rights'
description 'Installs/Configures diceware'
long_description 'Installs/Configures diceware'
version '0.1.0'

depends 'jhg_nginx'
depends 'app_node'
